accounts/urls.py
from django.urls import path
 
from .views import SignUpView
 
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path  
from . import views 
from .views import (
    BlogUpdateView,
    BlogCreateView
) 
  
app_name = 'blog' 
urlpatterns = [ 
    path('', views.post_list, name='post_list'),
    path('post/<int:pk>/edit/', BlogUpdateView.as_view(), name='post_edit'),
    path('post/new/', BlogCreateView.as_view(), name='post_new'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',  
         views.post_single,  
	     name='post_single'), 
]

newsitepr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'), name='blog'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from unicodedata import category
from django.db import models
from django.contrib.auth.models import User 
from django.utils import timezone 
from django.urls import reverse

# Create your models here.
class PublishedManager(models.Manager):  
    def get_queryset(self):  
        return super(PublishedManager,  
		     self).get_queryset().filter(status='published')

class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self): 
        return self.name   

class Post(models.Model):
    title = models.CharField(max_length=250)
    tag = models.SlugField(max_length=250, 
                            unique_for_date='publ_date')
    category = models.ForeignKey(Category, 
                                on_delete=models.CASCADE)
    body = models.TextField()                       
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE, 
                               related_name='blog_posts')       
    publ_date = models.DateTimeField(default=timezone.now)
    creat_date = models.DateTimeField(auto_now_add=True)  
    upd_date = models.DateTimeField(auto_now=True)
    STATUS_CHOICES = (
        ('draft', 'Draft'), 
        ('published', 'Published'), 
    )
    status = models.CharField(max_length=10, 
                              choices=STATUS_CHOICES, 
                              default='draft')
    objects = models.Manager()  # Менеджер по умолчанию  
    published = PublishedManager()  # Собственный менеджер
    
    class Meta: 
        ordering = ('-publ_date',) 

    def __str__(self): 
        return self.title
    
    def get_absolute_url(self):  
        return reverse('blog:post_single',  
		       args=[self.publ_date.year,  
                    self.publ_date.month,  
                    self.publ_date.day,  
                    self.tag])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blog/views.py
from django.shortcuts import render, get_object_or_404 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Category, Post 
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.text import slugify

# Create your views here.
def post_list(request): 
    page = request.GET.get('page')
    search = request.GET.get('search', '')
    if search != '':
        posts_list = Post.published.filter(category=search)
    else:
        posts_list = Post.published.all() 
        if len(posts_list) > 5:
            posts_list = Post.published.all()[0:5]
            
        
    paginator = Paginator(posts_list, 5)
    try:  
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    categories = Category.objects.all()
    return render(request, 'blog/post/list.html',  
                    {'page': page,  
                   'posts': posts, 
                   'categories' : categories})


def post_single(request, year, month, day, post):  
    post = get_object_or_404(Post, tag=post,  
                 status='published',  
                 publ_date__year=year,  
                 publ_date__month=month,  
                 publ_date__day=day) 
    return render(request,  
          'blog/post/singlepost.html',  
          {'post': post})

class BlogUpdateView(UpdateView):
    model = Post
    template_name = 'blog/post/post_edit.html'
    fields = ['title', 'body', 'category', 'status'] 

class BlogCreateView(LoginRequiredMixin, CreateView): 
    model = Post
    template_name = 'blog/post/post_new.html'
    fields = ['title', 'body', 'category' ,'status']     
    
    def form_valid(self, form):  
        form.instance.author = self.request.user
        form.instance.tag = slugify(form.instance.title)
        return super().form_valid(form)

blog/templates/blog/index.html
{% load static %}  
  
<!DOCTYPE html>  
<html>  
<head>  
  <!-- здесь будет блок, который можно заполнять в наследуемых файлах -->
  {% if user.is_authenticated %}
    Hi {{ user.username }}! <a href="{% url 'logout' %}">Выйти</a>
  {% else %}
    <a href="{% url 'login' %}">Войти</a>
    <a href="{% url 'signup' %}">Регистрация</a>
  {% endif %}
 <title>{% block title %}{% endblock %}</title>
 <link href="{% static 'css/index.css' %}" rel="stylesheet">  
</head>  
<body>  
  <div id="content">  
    {% block content %}  
        {% endblock %}  
      </div>  
  <div id="sidebar">  
    {% if user.is_authenticated %}
      <a href="{% url 'blog:post_new' %}">+ Создать новый пост</a>
    {% endif %}
    
    <h2>Блог и точка</h2>  
    <a href="{% url 'blog:post_list' %}">Домой</a>
    {% for cat in categories %} 
      <p><a href="{% url 'blog:post_list' %}?search={{cat.id}}">{{cat.name}}</a>
    {% endfor %} 
  </div>
</body>  
</html>

blog/templates/blog/pagination.html
<div class="pagination">  
    <span class="step-links">  
     {% if page.has_previous %}  
         <a href="?page={{ page.previous_page_number }}">Previous</a>  
     {% endif %}  
       <span class="current">  
     Page {{ page.number }} of {{ page.paginator.num_pages }}.  
       </span>  
     {% if page.has_next %}  
           <a href="?page={{ page.next_page_number }}">Next</a>  
     {% endif %}  
     </span>  
</div>

blog/templates/blog/post/list.html
<!-- наследование -->
{% extends "blog/index.html" %}  
  
{% block title %}My Blog{% endblock %}  
  
{% block content %}  
  <h1>Блог и точка</h1>  
  {% for post in posts %}  
    <h2>  
      <a href="{{ post.get_absolute_url }}">  
       {{ post.title }}  
      </a>  
    </h2> 
    <p class="date">  
      Published {{ post.publ_date }} by {{ post.author }}  
    </p>
    {% if user.id == post.author.id %}
      <a href="{% url 'blog:post_edit' post.pk %}">- Редактировать -</a> 
    {% endif %}
    <!-- truncateword оставляет только n-ое количество слов -->
    {{ post.body|truncatewords:30|linebreaks }}  
  {% endfor %} 
  {% include "../pagination.html" with page=posts %} 
{% endblock %}

blog/templates/blog/post/post_edit.html
{% extends 'index.html' %}
 
{% block content %}
    <h1>Редактировать запись</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
    <input type="submit" value="Изменить" />
</form>
{% endblock content %}

blog/templates/blog/post/post_new.html
{% extends 'index.html' %}
 
{% block content %}
    <h1>Создать пост</h1>
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Сохранить" />
    </form>
{% endblock content %}

blog/templates/blog/post/singlepost.html
{% extends "blog/index.html" %}  
  
{% block title %}{{ post.title }}{% endblock %}  
  
{% block content %}  
  <h1>{{ post.title }}</h1>  
  <p class="date">  
    Published {{ post.publish }} by {{ post.author }}  
  </p>  
  {{ post.body|linebreaks }}  
{% endblock %}

blog/templates/blog/signup.html
{% extends 'index.html' %}
 
{% block content %}
<h2>Зарегистрироваться</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Зарегистрироваться</button>
</form>
{% endblock content %}